<?php
use Gallery\Entity\Gallery;

$create = array('action' => 'create');
?>
<h1>Gallery</h1>
<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Thumburl</th>
        <th>Bigurl</th>
        <th><a href="<?php echo $this->url('gallery/action', $create) ?>">
                anlegen
            </a></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->galleryList as $gallery) : /* @var $gallery Gallery */ ?>
        <?php $show = array('action' => 'show', 'id' => $gallery->getId()); ?>
        <?php $update = array('action' => 'update', 'id' => $gallery->getId()); ?>
        <?php $delete = array('action' => 'delete', 'id' => $gallery->getId()); ?>
        <tr>
            <td><?php echo $gallery->getId(); ?></td>
            <td><?php echo $gallery->getTitle(); ?></td>
            <td><?php echo $gallery->getThumburl(); ?></td>
            <td><?php echo $gallery->getBigurl(); ?></td>
            <td><a href="<?php echo $this->url('gallery/action', $show) ?>">
                    anzeigen
                </a></td>
            <td><a href="<?php echo $this->url('gallery/action', $update) ?>">
                    ändern
                </a></td>
            <td><a href="<?php echo $this->url('gallery/action', $delete) ?>">
                    löschen
                </a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>